using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.ViewModels
{
    public class CourseVM
    {
        ////////////////////////////////////////////////////////////////////////////////////
        // The [DatabaseGenerated(DatabaseGeneratedOption.None)] attribute
        // specifies that the PK is provided by the application
        // rather than generated by the database.
        //
        // By default, EF Core assumes that PK values are generated by the database.
        // Database-generated is generally the best approach. For Course entities,
        // the user specifies the PK. For example, a course number such as a 1000 series
        // for the math department, a 2000 series for the English department.
        //////////////////////////////////////////////////////////////////////////////////
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Number")]
        public int CourseID { get; set; }


        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; }


        [Range(0, 5)]
        public int Credits { get; set; }

        public string DepartmentName { get; set; }


        public int DepartmentID { get; set; }


        //////////////////////////////////////////////////////////////////////////////
        // EF Core doesn't require a foreign key property for a data model
        // when the model has a navigation property for a related entity.
        // EF Core automatically creates FKs in the database wherever they're needed.
        // EF Core creates shadow properties for automatically created FKs.
        // However, explicitly including the FK in the data model can make updates
        // simpler and more efficient. 
        //
        // When the FK property DepartmentID is included in the data model,
        // there's no need to fetch the Department entity before an update.
        //////////////////////////////////////////////////////////////////////////////
        public DepartmentVM Department { get; set; }

        public ICollection<EnrollmentVM> Enrollments { get; set; }

        public ICollection<InstructorVM> Instructors { get; set; }
    }
}